apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Adjust as needed
  type: LoadBalancer
